### ISSUE TITLE
Not compatible with graylog2_exceptions

### ISSUE THREAD

**Issue by nirvdrum** [wr0ngway/log4r-gelf#2]
log4r-gelf has a dependency on gelf  ~> 1.1.3, while graylog2_exceptions has a dependency on gelf 1.3.  Since these two conflict, they can't both be installed at the same time.

**Comment by wr0ngway** [comment]
Added you as a collaborator - try running the tests after updating dependency and if its good, push it

**Comment by wr0ngway** [comment]
Changed dep to ~> 1.3
