### ISSUE TITLE
YAML options are expected to be symbols, doesn't match documentation

### ISSUE THREAD

**Issue by justindossey** [wr0ngway/log4r-gelf#3]
gelf_outputter.rb has lines like:

```
    opts['host'] = hash[:host] if hash[:host]
```

but hash is a Hash, not a HashWithIndifferentAccess.  Therefore, options from log4r.yaml are ignored unless specified as symbols.  You can either change the gelf_outputter to be like

```
    opts['host'] = hash['host'] if hash['host']
```

or change the documentation to say :facility instead of facility in yaml.  I vote for the former.

**Comment by wr0ngway** [comment]
Did some digging, seems log4r 1.1.10 broke a few things

https://github.com/colbygk/log4r/issues/10
https://github.com/colbygk/log4r/issues/11

Can't make a backwards compatible fix, so will release a new version that forces 1.1.10 dependency
